export const TIMELINE_SAMPLES_PER_PIXEL = 1024;
export const PLAYLIST_CONTROL_WIDTH = 180;
export const TIMELINE_ROW_HEIGHT = 92;
export const TIMELINE_RULER_HEIGHT = 52;
export const DEFAULT_TIMELINE_PADDING_SECONDS = 8;
